name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build the client Docker image
      run: docker build ./client --file ./client/Dockerfile --tag cohenpts/multi-client
    -
      name: Build the nginx Docker image
      run: docker build ./nginx --file ./nginx/Dockerfile --tag cohenpts/multi-nginx
    -
      name: Build the server Docker image
      run: docker build ./server --file ./server/Dockerfile --tag cohenpts/multi-server
    -
      name: Build the worker Docker image
      run: docker build ./worker --file ./worker/Dockerfile --tag cohenpts/multi-worker
    -
      name: Push the client docker image
      run: docker push cohenpts/multi-client
    -
      name: Push the nginx docker image
      run: docker push cohenpts/multi-nginx
    -
      name: Push the server docker image
      run: docker push cohenpts/multi-server
    -
      name: Push the worker docker image
      run: docker push cohenpts/multi-worker
