name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push client Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./client
        file: ./client/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: cohenpts/multi-client:latest
    -
      name: Build and push nginx Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./nginx
        file: ./nginx/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: cohenpts/multi-nginx:latest
    -
      name: Build and push server Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./server
        file: ./server/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: cohenpts/multi-server:latest
    -
      name: Build and push worker Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./worker
        file: ./worker/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: cohenpts/multi-worker:latest
